/* SPDX-License-Identifier: BSD-3-Clause */
/*
 * Copyright (c) 2019 Fuzhou Rockchip Electronics Co., Ltd
 */

/** @addtogroup RK_HAL_Driver
 *  @{
 */

/** @addtogroup ACDCDIG
 *  @{
 */

#ifndef _HAL_ACDCDIG_H_
#define _HAL_ACDCDIG_H_

#include "hal_audio.h"
#include "hal_def.h"

/***************************** MACRO Definition ******************************/
/** @defgroup ACDCDIG_Exported_Definition_Group1 Basic Definition
 *  @{
 */

/* VUCTL */
#define ACDCDIG_VUCTL_ADCZDT_EN   (0x1U << ACDCDIG_VUCTL_ADCZDT_SHIFT)
#define ACDCDIG_VUCTL_ADCFADE_EN  (0x1U << ACDCDIG_VUCTL_ADCFADE_SHIFT)
#define ACDCDIG_VUCTL_ADC_BYPS_EN (0x1U << ACDCDIG_VUCTL_ADC_BYPS_SHIFT)
/* VUCTIME */
#define ACDCDIG_VUCTIME_VUCT(x) ((x) << ACDCDIG_VUCTIME_VUCT_SHIFT)
/* DIGEN */
#define ACDCDIG_DIGEN_I2STX_DIS (0x0U << ACDCDIG_DIGEN_I2STX_EN_SHIFT)
#define ACDCDIG_DIGEN_I2STX_EN  (0x1U << ACDCDIG_DIGEN_I2STX_EN_SHIFT)
#define ACDCDIG_DIGEN_ADC_DIS   (0x0U << ACDCDIG_DIGEN_ADC_EN_SHIFT)
#define ACDCDIG_DIGEN_ADC_EN    (0x1U << ACDCDIG_DIGEN_ADC_EN_SHIFT)
/* CLKCTRL */
#define ACDCDIG_CLKCTRL_FILTER_GATE_EN  (0x1U << ACDCDIG_CLKCTRL_FILTER_GATE_EN_SHIFT)
#define ACDCDIG_CLKCTRL_CKE_BCLK_DIS    (0x0U << ACDCDIG_CLKCTRL_CKE_BCLK_SHIFT)
#define ACDCDIG_CLKCTRL_CKE_BCLK_EN     (0x1U << ACDCDIG_CLKCTRL_CKE_BCLK_SHIFT)
#define ACDCDIG_CLKCTRL_I2STX_CKE_DIS   (0x0U << ACDCDIG_CLKCTRL_I2STX_CKE_SHIFT)
#define ACDCDIG_CLKCTRL_I2STX_CKE_EN    (0x1U << ACDCDIG_CLKCTRL_I2STX_CKE_SHIFT)
#define ACDCDIG_CLKCTRL_ADC_CKE_DIS     (0x0U << ACDCDIG_CLKCTRL_ADC_CKE_SHIFT)
#define ACDCDIG_CLKCTRL_ADC_CKE_EN      (0x1U << ACDCDIG_CLKCTRL_ADC_CKE_SHIFT)
#define ACDCDIG_CLKCTRL_CIC_DS_RATIO_16 (0x0U << ACDCDIG_CLKCTRL_CIC_DS_RATIO_SHIFT)
#define ACDCDIG_CLKCTRL_CIC_DS_RATIO_8  (0x1U << ACDCDIG_CLKCTRL_CIC_DS_RATIO_SHIFT)
#define ACDCDIG_CLKCTRL_CIC_DS_RATIO_4  (0x2U << ACDCDIG_CLKCTRL_CIC_DS_RATIO_SHIFT)
/* CLKDIV */
#define ACDCDIG_CLKDIV_INT_DIV_CON(x) ((x - 1) << ACDCDIG_CLKDIV_INT_DIV_CON_SHIFT)
/* REFCFG */
#define ACDCDIG_REFCFG_REF_TOP_TRIM(x) ((x) << ACDCDIG_REFCFG_REF_TOP_TRIM_SHIFT)
#define ACDCDIG_REFCFG_REF_ANA_TRIM(x) ((x) << ACDCDIG_REFCFG_REF_ANA_TRIM_SHIFT)
#define ACDCDIG_REFCFG_REF_TOP_PWU     (0x0U << ACDCDIG_REFCFG_REF_TOP_PWD_SHIFT)
#define ACDCDIG_REFCFG_REF_TOP_PWD     (0x1U << ACDCDIG_REFCFG_REF_TOP_PWD_SHIFT)
/* ADCCFG0 */
#define ACDCDIG_ADCCFG0_ADC_DITH_SEL(x)    ((x) << ACDCDIG_ADCCFG0_ADC_DITH_SEL_SHIFT)
#define ACDCDIG_ADCCFG0_ADC_DITH_EN        (0x1U << ACDCDIG_ADCCFG0_ADC_DITH_EN_SHIFT)
#define ACDCDIG_ADCCFG0_ADC_CHOP_CLK_1200K (0x0U << ACDCDIG_ADCCFG0_ADC_CHOP_CLK_SEL_SHIFT)
#define ACDCDIG_ADCCFG0_ADC_CHOP_CLK_600K  (0x1U << ACDCDIG_ADCCFG0_ADC_CHOP_CLK_SEL_SHIFT)
#define ACDCDIG_ADCCFG0_ADC_CHOP_EN        (0x1U << ACDCDIG_ADCCFG0_ADC_CHOP_EN_SHIFT)
#define ACDCDIG_ADCCFG0_ADC_PWU_R          (0x0U << ACDCDIG_ADCCFG0_ADC_PWD_R_SHIFT)
#define ACDCDIG_ADCCFG0_ADC_PWD_R          (0x1U << ACDCDIG_ADCCFG0_ADC_PWD_R_SHIFT)
#define ACDCDIG_ADCCFG0_ADC_PWU_L          (0x0U << ACDCDIG_ADCCFG0_ADC_PWD_L_SHIFT)
#define ACDCDIG_ADCCFG0_ADC_PWD_L          (0x1U << ACDCDIG_ADCCFG0_ADC_PWD_L_SHIFT)
/* ADCCFG1 */
#define ACDCDIG_ADCCFG1_ADC_BOOST_VAGOP   (0x1U << ACDCDIG_ADCCFG1_ADC_BOOST_VAGOP_SHIFT)
#define ACDCDIG_ADCCFG1_ADC_BOOST_OPAMP   (0x1U << ACDCDIG_ADCCFG1_ADC_BOOST_OPAMP_SHIFT)
#define ACDCDIG_ADCCFG1_ADC_ATTN_OPBIAS   (0x1U << ACDCDIG_ADCCFG1_ADC_ATTN_OPBIAS_SHIFT)
#define ACDCDIG_ADCCFG1_ADC_ATTN_ALLIBIAS (0x1U << ACDCDIG_ADCCFG1_ADC_ATTN_ALLIBIAS_SHIFT)
/* ADCCFG2 */
#define ACDCDIG_ADCCFG2_CT_ADC_BOOST   (0x1U << ACDCDIG_ADCCFG2_CT_ADC_BOOST_SHIFT)
#define ACDCDIG_ADCCFG2_CT_ADC_ATTN    (0x1U << ACDCDIG_ADCCFG2_CT_ADC_ATTN_SHIFT)
#define ACDCDIG_ADCCFG2_CT_ADC_ATTN_OP (0x1U << ACDCDIG_ADCCFG2_CT_ADC_ATTN_OP_SHIFT)
#define ACDCDIG_ADCCFG2_ADC_OUT_SEL_DS (0x0U << ACDCDIG_ADCCFG2_ADC_OUT_SEL_SHIFT)
#define ACDCDIG_ADCCFG2_ADC_OUT_SEL_CT (0x1U << ACDCDIG_ADCCFG2_ADC_OUT_SEL_SHIFT)
#define ACDCDIG_ADCCFG2_CT_ADC_ZERO    (0x1U << ACDCDIG_ADCCFG2_CT_ADC_ZERO_SHIFT)
#define ACDCDIG_ADCCFG2_CT_ADC_PWU     (0x0U << ACDCDIG_ADCCFG2_CT_ADC_PWD_SHIFT)
#define ACDCDIG_ADCCFG2_CT_ADC_PWD     (0x1U << ACDCDIG_ADCCFG2_CT_ADC_PWD_SHIFT)
/* ADCCFG3 */
#define ACDCDIG_ADCCFG3_FIR_COM_BPS    (0x1U << ACDCDIG_ADCCFG3_FIR_COM_BPS_SHIFT)
#define ACDCDIG_ADCCFG3_SIG_SCALE_MODE (0x1U << ACDCDIG_ADCCFG3_SIG_SCALE_MODE_SHIFT)
#define ACDCDIG_ADCCFG3_ADCSRT(x)      ((x) << ACDCDIG_ADCCFG3_ADCSRT_SHIFT)
/* ADCVOLL */
#define ACDCDIG_ADCVOLL_ADCLV(x) ((x) << ACDCDIG_ADCVOLL_ADCLV_SHIFT)
/* ADCVOLR */
#define ACDCDIG_ADCVOLR_ADCRV(x) ((x) << ACDCDIG_ADCVOLR_ADCRV_SHIFT)
/* ALC0 */
#define ACDCDIG_ALC0_ADCRV_GAIN_POL_NEGATIVE (0x0U << ACDCDIG_ALC0_ADCRV_GAIN_POL_SHIFT)
#define ACDCDIG_ALC0_ADCRV_GAIN_POL_POSITIVE (0x1U << ACDCDIG_ALC0_ADCRV_GAIN_POL_SHIFT)
#define ACDCDIG_ALC0_ADCLV_GAIN_POL_NEGATIVE (0x0U << ACDCDIG_ALC0_ADCLV_GAIN_POL_SHIFT)
#define ACDCDIG_ALC0_ADCLV_GAIN_POL_POSITIVE (0x1U << ACDCDIG_ALC0_ADCLV_GAIN_POL_SHIFT)
#define ACDCDIG_ALC0_ALCR_EN                 (0x1U << ACDCDIG_ALC0_ALCR_SHIFT)
#define ACDCDIG_ALC0_ALCL_EN                 (0x1U << ACDCDIG_ALC0_ALCL_SHIFT)
/* ALC1 */
#define ACDCDIG_ALC1_ALCRRATE(x) ((x) << ACDCDIG_ALC1_ALCRRATE_SHIFT)
#define ACDCDIG_ALC1_ALCARATE(x) ((x) << ACDCDIG_ALC1_ALCARATE_SHIFT)
/* ALC2 */
#define ACDCDIG_ALC2_ALCMIN(x)  ((x) << ACDCDIG_ALC2_ALCMIN_SHIFT)
#define ACDCDIG_ALC2_ALCMAX(x)  ((x) << ACDCDIG_ALC2_ALCMAX_SHIFT)
#define ACDCDIG_ALC2_NGVALID_NG (0x1U << ACDCDIG_ALC2_NGVALID_SHIFT)
/* ADCNG */
#define ACDCDIG_ADCNG_NGDLY(x)      ((x) << ACDCDIG_ADCNG_NGDLY_SHIFT)
#define ACDCDIG_ADCNG_NGGATE(x)     ((x) << ACDCDIG_ADCNG_NGGATE_SHIFT)
#define ACDCDIG_ADCNG_NGBOOST_BOOST (0x1U << ACDCDIG_ADCNG_NGBOOST_SHIFT)
#define ACDCDIG_ADCNG_NGEN          (0x1U << ACDCDIG_ADCNG_NGEN_SHIFT)
#define ACDCDIG_ADCNG_NGCHL_BOTH    (0x1U << ACDCDIG_ADCNG_NGCHL_SHIFT)
/* HPFCTRL */
#define ACDCDIG_HPFCTRL_HPFCF(x) ((x) << ACDCDIG_HPFCTRL_HPFCF_SHIFT)
#define ACDCDIG_HPFCTRL_HPFRE_EN (0x1U << ACDCDIG_HPFCTRL_HPFRE_SHIFT)
#define ACDCDIG_HPFCTRL_HPFLE_EN (0x1U << ACDCDIG_HPFCTRL_HPFLE_SHIFT)
/* PGACFG */
#define ACDCDIG_PGACFG_PGA_R_DEC(x) ((x / 3) << ACDCDIG_PGACFG_PGA_R_DEC_SHIFT)
#define ACDCDIG_PGACFG_PGA_L_DEC(x) ((x / 3) << ACDCDIG_PGACFG_PGA_L_DEC_SHIFT)
#define ACDCDIG_PGACFG_PGA_R_PU     (0x0U << ACDCDIG_PGACFG_PGA_R_PD_SHIFT)
#define ACDCDIG_PGACFG_PGA_R_PD     (0x1U << ACDCDIG_PGACFG_PGA_R_PD_SHIFT)
#define ACDCDIG_PGACFG_PGA_L_PU     (0x0U << ACDCDIG_PGACFG_PGA_L_PD_SHIFT)
#define ACDCDIG_PGACFG_PGA_L_PD     (0x1U << ACDCDIG_PGACFG_PGA_L_PD_SHIFT)
#define ACDCDIG_PGACFG_PGA_CHOP_EN  (0x1U << ACDCDIG_PGACFG_PGA_CHOP_EN_SHIFT)
/* PGAGAINL */
#define ACDCDIG_PGAGAINL_PGA_GAIN_L(x) ((x) << ACDCDIG_PGAGAINL_PGA_GAIN_L_SHIFT)
/* PGAGAINR */
#define ACDCDIG_PGAGAINR_PGA_GAIN_R(x) ((x) << ACDCDIG_PGAGAINR_PGA_GAIN_R_SHIFT)
/* LILMT1 */
#define ACDCDIG_LILMT1_MIN_LILMT(x) ((x) << ACDCDIG_LILMT1_MIN_LILMT_SHIFT)
#define ACDCDIG_LILMT1_MAX_LILMT(x) ((x) << ACDCDIG_LILMT1_MAX_LILMT_SHIFT)
#define ACDCDIG_LILMT1_LMT_EN       (0x1U << ACDCDIG_LILMT1_LMT_EN_SHIFT)
/* LILMT2 */
#define ACDCDIG_LILMT2_RLS_RATE(x) ((x) << ACDCDIG_LILMT2_RLS_RATE_SHIFT)
#define ACDCDIG_LILMT2_ATK_RATE(x) ((x) << ACDCDIG_LILMT2_ATK_RATE_SHIFT)
/* LILMTNG1 */
#define ACDCDIG_LILMTNG1_NGDLY_LI(x)      ((x) << ACDCDIG_LILMTNG1_NGDLY_LI_SHIFT)
#define ACDCDIG_LILMTNG1_NGGATE_LI(x)     ((x) << ACDCDIG_LILMTNG1_NGGATE_LI_SHIFT)
#define ACDCDIG_LILMTNG1_NGBOOST_LI_BOOST (0x1U << ACDCDIG_LILMTNG1_NGBOOST_LI_SHIFT)
#define ACDCDIG_LILMTNG1_NGEN_LI_EN       (0x1U << ACDCDIG_LILMTNG1_NGEN_LI_SHIFT)
#define ACDCDIG_LILMTNG1_NGCHL_LI_BOTH    (0x1U << ACDCDIG_LILMTNG1_NGCHL_LI_SHIFT)
/* LILMTNG2 */
#define ACDCDIG_LILMTNG2_NGVALID_LI_NG (0x1U << ACDCDIG_LILMTNG2_NGVALID_LI_SHIFT)
/* PDMCTRL */
#define ACDCDIG_PDMCTRL_PDM_LR_SWITCH (0x1U << ACDCDIG_PDMCTRL_PDM_LR_SEL_SHIFT)
#define ACDCDIG_PDMCTRL_PDM_MODE_I2S  (0x0U << ACDCDIG_PDMCTRL_PDM_MODE_SHIFT)
#define ACDCDIG_PDMCTRL_PDM_MODE_PDM  (0x1U << ACDCDIG_PDMCTRL_PDM_MODE_SHIFT)
#define ACDCDIG_PDMCTRL_PDM_DIS       (0x1U << ACDCDIG_PDMCTRL_PDM_EN_SHIFT)
#define ACDCDIG_PDMCTRL_PDM_EN        (0x1U << ACDCDIG_PDMCTRL_PDM_EN_SHIFT)
/* I2SCKM */
#define ACDCDIG_I2SCKM_I2SMST_SLAVE  (0x0U << ACDCDIG_I2SCKM_I2SMST_SHIFT)
#define ACDCDIG_I2SCKM_I2SMST_MASTER (0x1U << ACDCDIG_I2SCKM_I2SMST_SHIFT)
#define ACDCDIG_I2SCKM_SCK_P_INV     (0x1U << ACDCDIG_I2SCKM_SCK_P_SHIFT)
/* I2SDIV */
#define ACDCDIG_I2SDIV_SCKDIV(x) ((x) << ACDCDIG_I2SDIV_SCKDIV_SHIFT)
/* I2STXCR0 */
#define ACDCDIG_I2STXCR0_TXRL_P_INV (0x1U << ACDCDIG_I2STXCR0_TXRL_P_SHIFT)
#define ACDCDIG_I2STXCR0_SCKDTX_64  (0x0U << ACDCDIG_I2STXCR0_SCKDTX_SHIFT)
#define ACDCDIG_I2STXCR0_SCKDTX_128 (0x1U << ACDCDIG_I2STXCR0_SCKDTX_SHIFT)
#define ACDCDIG_I2STXCR0_SCKDTX_256 (0x2U << ACDCDIG_I2STXCR0_SCKDTX_SHIFT)
/* I2STXCR1 */
#define ACDCDIG_I2STXCR1_LSB        (0x1U << ACDCDIG_I2STXCR1_LSB_SHIFT)
#define ACDCDIG_I2STXCR1_SWITCH     (0x1U << ACDCDIG_I2STXCR1_EXRL_SHIFT)
#define ACDCDIG_I2STXCR1_IBM_NORMAL (0x0U << ACDCDIG_I2STXCR1_IBM_SHIFT)
#define ACDCDIG_I2STXCR1_IBM_LJ     (0x1U << ACDCDIG_I2STXCR1_IBM_SHIFT)
#define ACDCDIG_I2STXCR1_IBM_RJ     (0x2U << ACDCDIG_I2STXCR1_IBM_SHIFT)
#define ACDCDIG_I2STXCR1_PBM_EARLY  (0x0U << ACDCDIG_I2STXCR1_PBM_SHIFT)
#define ACDCDIG_I2STXCR1_PBM_LATE1  (0x1U << ACDCDIG_I2STXCR1_PBM_SHIFT)
#define ACDCDIG_I2STXCR1_PBM_LATE2  (0x2U << ACDCDIG_I2STXCR1_PBM_SHIFT)
#define ACDCDIG_I2STXCR1_PBM_LATE3  (0x3U << ACDCDIG_I2STXCR1_PBM_SHIFT)
#define ACDCDIG_I2STXCR1_TFS_I2S    (0x0U << ACDCDIG_I2STXCR1_TFS_SHIFT)
#define ACDCDIG_I2STXCR1_TFS_PCM    (0x1U << ACDCDIG_I2STXCR1_TFS_SHIFT)
/* I2STXCR2 */
#define ACDCDIG_I2STXCR2_VDW(x) ((x - 1) << ACDCDIG_I2STXCR2_VDW_SHIFT)
/* I2STXCMD */
#define ACDCDIG_I2STXCMD_RCNT(x)   ((x) << ACDCDIG_I2STXCMD_RCNT_SHIFT)
#define ACDCDIG_I2STXCMD_TXC       (0x1U << ACDCDIG_I2STXCMD_TXC_SHIFT)
#define ACDCDIG_I2STXCMD_TXS_STOP  (0x0U << ACDCDIG_I2STXCMD_TXS_SHIFT)
#define ACDCDIG_I2STXCMD_TXS_START (0x1U << ACDCDIG_I2STXCMD_TXS_SHIFT)

/***************************** Structure Definition **************************/

/** acdcDig dev struct */
struct HAL_ACDCDIG_DEV {
    struct ACDCDIG_REG *reg;
    uint32_t hclk;
    eAUDIO_fmtType format;
};

/** @} */
/***************************** Function Declare ******************************/

HAL_Status HAL_ACDCDIG_Supsend(struct HAL_ACDCDIG_DEV *acdcDig);
HAL_Status HAL_ACDCDIG_Resume(struct HAL_ACDCDIG_DEV *acdcDig);
HAL_Status HAL_ACDCDIG_Init(struct HAL_ACDCDIG_DEV *acdcDig, struct AUDIO_INIT_CONFIG *config);
HAL_Status HAL_ACDCDIG_DeInit(struct HAL_ACDCDIG_DEV *acdcDig);
HAL_Status HAL_ACDCDIG_Enable(struct HAL_ACDCDIG_DEV *acdcDig);
HAL_Status HAL_ACDCDIG_Disable(struct HAL_ACDCDIG_DEV *acdcDig);
HAL_Status HAL_ACDCDIG_Config(struct HAL_ACDCDIG_DEV *acdcDig, struct AUDIO_PARAMS *params);

#endif

/** @} */

/** @} */
