# SPDX -License-Identifier: BSD-3-Clause */

# Copyright (c) 2021 Rockchip Electronics Co., Ltd.

PROJECT := RK3568
SOC := RK3568
CPU = -march=armv8-a -mtune=cortex-a55

include ../../../middleware/sdhci/sdhci.mk
include ../../common/GCC/Cortex-A.mk
