# SPDX-License-Identifier: BSD-3-Clause */

# Copyright (c) 2020 Rockchip Electronics Co., Ltd.

PROJECT		:= RK3588
SOC		:= RK3588
CPU		:= -mcpu=cortex-m0 -mthumb
LINKER_SCRIPT   := ../../../lib/CMSIS/Device/$(SOC)/Source/Templates/GCC/gcc_m0.ld

include ../../common/GCC/Cortex-M.mk
