# SPDX-License-Identifier: BSD-3-Clause */

# Copyright (c) 2019 Fuzhou Rockchip Electronics Co., Ltd

PROJECT		:= RV1126
CPU		:= -march=rv32imac -mabi=ilp32 -DARCH_RISCV

include ../../common/GCC/riscv.mk
